version: "3"
services:
  # database:
  #   image: postgis/postgis:16-master
  #   restart: always
  #   ports:
  #     - 5432:5432
  #   # Required when running on platform other than amd64, like Apple M1/M2:
  #   # platform: linux/amd64
  #   volumes:
  #     - ./database:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: "postgres"
  #     POSTGRES_PASSWORD: "postgres"
  #     POSTGRES_DB: "termini.si"

  directus:
    # image: directus/directus:10.12.1
    build:
      context: ./
    restart: always
    # depends_on:
    #   - database
    ports:
      - 8055:8055
    volumes:
      # - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
      - ./snapshots:/directus/snapshots
    environment:
      SECRET: "replace-with-secure-random-value"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      DB_CLIENT: "pg"
      DB_HOST: "aws-0-eu-central-1.pooler.supabase.com"
      DB_PORT: "6543"
      DB_USER: "postgres.kwqunocvrqnbwlqvjtxa"
      DB_PASSWORD: "sevhOkU9AZVWFnvZ"
      DB_DATABASE: "postgres"
      WEBSOCKETS_ENABLED: "true"

      EXTENSIONS_AUTO_RELOAD: "true"

      CORS_ENABLED: "true"
      CORS_ORIGIN: "http://localhost:3000"

      STORAGE_LOCATIONS: "s3"
      STORAGE_S3_DRIVER: "s3"
      STORAGE_S3_KEY: "e614bdaedfba5b217e63d047898c2184"
      STORAGE_S3_SECRET: "d2ce3998609d9bb92556fd693396f628082ebf80ea743fb682d57235b800b032"
      STORAGE_S3_ENDPOINT: "https://43618a8104c6c47513ac3ef37665f8ac.r2.cloudflarestorage.com/local-termini-si"
      STORAGE_S3_BUCKET: "local-termini-si"
      STORAGE_S3_REGION: "auto"
      STORAGE_S3_ROOT: "assets"

      ACCESS_TOKEN_TTL: "3d"

      STRIPE_SECRET_KEY: "sk_test_51LUUJEEaQ0gJxeyLABg1s1Q0Wx02qoHHmQIJJ32yX8gF5XStdrPgZfJ03wIG9J3YOpCDivi5zXAR22SlU5N6ppAz00C55fuEae"
      STRIPE_PAYMENT_WEBHOOK_SECRET: "whsec_ed90c136de7004dc2e48be1eee5971b520b0245c683af2e552083fe9ad72e930"

      WEATHER_API_KEY: "86B4HEALAPW3U5H8S3K2PVN3S"
volumes:
  directus_uploads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./uploads
  directus_extensions:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./extensions
  directus_snapshots:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./snapshots
