version: "3"
services:
  database:
    image: postgis/postgis:16-master
    restart: always
    ports:
      - 5432:5432
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "termini.si"

  directus:
    # image: directus/directus:10.12.1
    build:
      context: ./
    depends_on:
      - database
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      SECRET: "replace-with-secure-random-value"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_DATABASE: "termini.si"
      WEBSOCKETS_ENABLED: "true"

      EXTENSIONS_AUTO_RELOAD: "true"

      CORS_ENABLED: "true"
      CORS_ORIGIN: "http://localhost:3000"

      STORAGE_LOCATIONS: "s3"
      STORAGE_S3_DRIVER: "s3"
      STORAGE_S3_KEY: "1fe6a2b1dbfd22888a2965d39e7d1f73"
      STORAGE_S3_SECRET: "21582e18947bade8481d3f4e9aa3bcd3d7d863ab8ce936924b0799d50b6f2c27"
      STORAGE_S3_ENDPOINT: "https://43618a8104c6c47513ac3ef37665f8ac.r2.cloudflarestorage.com"
      STORAGE_S3_BUCKET: "sport-reserve"
      STORAGE_S3_REGION: "auto"
      STORAGE_S3_ROOT: "assets"

      ACCESS_TOKEN_TTL: "3d"

      STRIPE_SECRET_KEY: "sk_test_51LUUJEEaQ0gJxeyLABg1s1Q0Wx02qoHHmQIJJ32yX8gF5XStdrPgZfJ03wIG9J3YOpCDivi5zXAR22SlU5N6ppAz00C55fuEae"
      STRIPE_PAYMENT_WEBHOOK_SECRET: "whsec_ed90c136de7004dc2e48be1eee5971b520b0245c683af2e552083fe9ad72e930"

      WEATHER_API_KEY: "86B4HEALAPW3U5H8S3K2PVN3S"
volumes:
  directus_uploads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./uploads
  directus_extensions:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./extensions
